apiVersion: v1
kind: Service
metadata:
    name: "nas-079e"
    labels:
        app: "nas-079e"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "nas-079e"