apiVersion: v1
kind: Service
metadata:
    name: "nastasia2-2b41"
    labels:
        app: "nastasia2-2b41"
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: "nastasia2-2b41"